on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

  workflow_dispatch:

jobs:
  check:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright
      run: pnpm dlx playwright install --with-deps

    - name: Build Storybook
      run: pnpm build-storybook --quiet

    - name: Serve Storybook and run tests
      run: |
        pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "pnpm dlx http-server storybook-static --port 6006 --silent" \
          "pnpm dlx wait-on tcp:6006 && pnpm test-storybook"
