export const STORYBOOK_SUBJECT_ID = 302286;
export const STORYBOOK_NOT_COLLECTED_SUBJECT_ID = 2617;

export const STORYBOOK_BROKEN_SUBJECT_ID = 899;
export const STORYBOOK_BROKEN_NOT_COLLECTED_SUBJECT_ID = 975;

export const STORYBOOK_UPCOMING_SUBJECT_ID = 412916;

export const STORYBOOK_USERNAME_ID = "sai";
