import { cn } from "@/lib/utils";

export const WrappedColor = () => (
  <div
    className={cn(
      "border-primary-1 border-primary-2 border-primary-3 border-primary-4 border-primary-5 border-primary-6 border-primary-7 border-primary-8 border-primary-9 border-primary-10 border-primary-11 border-primary-12 border-accent-1 border-accent-2 border-accent-3 border-accent-4 border-accent-5 border-accent-6 border-accent-7 border-accent-8 border-accent-9 border-accent-10 border-accent-11 border-accent-12 border-neutral-1 border-neutral-2 border-neutral-3 border-neutral-4 border-neutral-5 border-neutral-6 border-neutral-7 border-neutral-8 border-neutral-9 border-neutral-10 border-neutral-11 border-neutral-12",
      "bg-primary-1 bg-primary-2 bg-primary-3 bg-primary-4 bg-primary-5 bg-primary-6 bg-primary-7 bg-primary-8 bg-primary-9 bg-primary-10 bg-primary-11 bg-primary-12 bg-accent-1 bg-accent-2 bg-accent-3 bg-accent-4 bg-accent-5 bg-accent-6 bg-accent-7 bg-accent-8 bg-accent-9 bg-accent-10 bg-accent-11 bg-accent-12 bg-neutral-1 bg-neutral-2 bg-neutral-3 bg-neutral-4 bg-neutral-5 bg-neutral-6 bg-neutral-7 bg-neutral-8 bg-neutral-9 bg-neutral-10 bg-neutral-11 bg-neutral-12 bg-success-1 bg-success-2 bg-success-3 bg-success-4 bg-success-5 bg-success-6 bg-success-7 bg-success-8 bg-success-9 bg-success-10 bg-success-11 bg-success-12",
      "text-primary-1 text-primary-2 text-primary-3 text-primary-4 text-primary-5 text-primary-6 text-primary-7 text-primary-8 text-primary-9 text-primary-10 text-primary-11 text-primary-12 text-accent-1 text-accent-2 text-accent-3 text-accent-4 text-accent-5 text-accent-6 text-accent-7 text-accent-8 text-accent-9 text-accent-10 text-accent-11 text-accent-12 text-neutral-1 text-neutral-2 text-neutral-3 text-neutral-4 text-neutral-5 text-neutral-6 text-neutral-7 text-neutral-8 text-neutral-9 text-neutral-10 text-neutral-11 text-neutral-12 text-success-1 text-success-2 text-success-3 text-success-4 text-success-5 text-success-6 text-success-7 text-success-8 text-success-9 text-success-10 text-success-11 text-success-12",
      "hover:bg-primary-1 hover:bg-primary-2 hover:bg-primary-3 hover:bg-primary-4 hover:bg-primary-5 hover:bg-primary-6 hover:bg-primary-7 hover:bg-primary-8 hover:bg-primary-9 hover:bg-primary-10 hover:bg-primary-11 hover:bg-primary-12 hover:bg-accent-1 hover:bg-accent-2 hover:bg-accent-3 hover:bg-accent-4 hover:bg-accent-5 hover:bg-accent-6 hover:bg-accent-7 hover:bg-accent-8 hover:bg-accent-9 hover:bg-accent-10 hover:bg-accent-11 hover:bg-accent-12 hover:bg-neutral-1 hover:bg-neutral-2 hover:bg-neutral-3 hover:bg-neutral-4 hover:bg-neutral-5 hover:bg-neutral-6 hover:bg-neutral-7 hover:bg-neutral-8 hover:bg-neutral-9 hover:bg-neutral-10 hover:bg-neutral-11 hover:bg-neutral-12 hover:bg-success-1 hover:bg-success-2 hover:bg-success-3 hover:bg-success-4 hover:bg-success-5 hover:bg-success-6 hover:bg-success-7 hover:bg-success-8 hover:bg-success-9 hover:bg-success-10 hover:bg-success-11 hover:bg-success-12",
      "active:bg-primary-1 active:bg-primary-2 active:bg-primary-3 active:bg-primary-4 active:bg-primary-5 active:bg-primary-6 active:bg-primary-7 active:bg-primary-8 active:bg-primary-9 active:bg-primary-10 active:bg-primary-11 active:bg-primary-12 active:bg-accent-1 active:bg-accent-2 active:bg-accent-3 active:bg-accent-4 active:bg-accent-5 active:bg-accent-6 active:bg-accent-7 active:bg-accent-8 active:bg-accent-9 active:bg-accent-10 active:bg-accent-11 active:bg-accent-12 active:bg-neutral-1 active:bg-neutral-2 active:bg-neutral-3 active:bg-neutral-4 active:bg-neutral-5 active:bg-neutral-6 active:bg-neutral-7 active:bg-neutral-8 active:bg-neutral-9 active:bg-neutral-10 active:bg-neutral-11 active:bg-neutral-12 active:bg-success-1 active:bg-success-2 active:bg-success-3 active:bg-success-4 active:bg-success-5 active:bg-success-6 active:bg-success-7 active:bg-success-8 active:bg-success-9 active:bg-success-10 active:bg-success-11 active:bg-success-12",
      "focus:bg-primary-1 focus:bg-primary-2 focus:bg-primary-3 focus:bg-primary-4 focus:bg-primary-5 focus:bg-primary-6 focus:bg-primary-7 focus:bg-primary-8 focus:bg-primary-9 focus:bg-primary-10 focus:bg-primary-11 focus:bg-primary-12 focus:bg-accent-1 focus:bg-accent-2 focus:bg-accent-3 focus:bg-accent-4 focus:bg-accent-5 focus:bg-accent-6 focus:bg-accent-7 focus:bg-accent-8 focus:bg-accent-9 focus:bg-accent-10 focus:bg-accent-11 focus:bg-accent-12 focus:bg-neutral-1 focus:bg-neutral-2 focus:bg-neutral-3 focus:bg-neutral-4 focus:bg-neutral-5 focus:bg-neutral-6 focus:bg-neutral-7 focus:bg-neutral-8 focus:bg-neutral-9 focus:bg-neutral-10 focus:bg-neutral-11 focus:bg-neutral-12 focus:bg-success-1 focus:bg-success-2 focus:bg-success-3 focus:bg-success-4 focus:bg-success-5 focus:bg-success-6 focus:bg-success-7 focus:bg-success-8 focus:bg-success-9 focus:bg-success-10 focus:bg-success-11 focus:bg-success-12"
    )}
  ></div>
);
